# Generated by Django 3.0.8 on 2020-07-04 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street', models.CharField(max_length=500)),
                ('postal_code', models.CharField(max_length=20)),
                ('number', models.CharField(max_length=10)),
                ('state', models.CharField(max_length=500)),
                ('neighborhood', models.CharField(max_length=500)),
                ('reference', models.CharField(max_length=500)),
            ],
            options={
                'db_table': 'address',
            },
        ),
    ]
