# Generated by Django 3.0.8 on 2020-07-04 14:46

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_seller'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=datetime.datetime.now)),
                ('collect_at', models.DateTimeField(blank=True)),
                ('delivery_at', models.DateTimeField(blank=True)),
                ('status', models.CharField(max_length=500)),
                ('destination_address', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='destination', to='app.Address')),
                ('origin_address', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='origin', to='app.Address')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app.Product')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app.Seller')),
            ],
            options={
                'db_table': 'order',
            },
        ),
    ]
