# Generated by Django 3.0.8 on 2020-07-04 17:36

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=datetime.datetime.now)),
                ('collected_at', models.DateTimeField(blank=True)),
                ('status', models.CharField(max_length=500)),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app.Address')),
                ('deliveryman', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app.Seller')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app.Order')),
            ],
            options={
                'db_table': 'route',
            },
        ),
    ]
