# Generated by Django 3.0.8 on 2020-07-04 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_route'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='price',
            field=models.FloatField(default=0.0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='risk',
            field=models.TextField(default="low"),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='volume',
            field=models.TextField(),
        ),
    ]
